### ISSUE TITLE
Send notification

### ISSUE THREAD

**Issue by La0** [mozilla/task-boot#64]
Taskboot should be able to auto-magically send Slack notifications when a deployment action is done (docker push, deploy on S3, Taskcluster artifact or Heroku).

A shared optional argument `--notify` (with default to env variable `NOTIFY`) could be used here.
The secret will need to have a `slack` configuration such as:

```yaml
slack:
  token: secretXXX
  channel: my-team-channel
```
